# Generated by Django 5.0.1 on 2024-01-05 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0002_film_filmrating'),
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramUserState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_id', models.IntegerField(blank=True, db_index=True, null=True, unique=True)),
                ('state', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
